export default 
{
    actorName: ['Ida Phantom', 'Grace Fast Fingers', 'Clotilde the Menace', 'Lucky Elizabeth',
                'Three Toed Kaleigh', 'Bullseye Karli', 'Eva the Bug', 'Cheating Cayla'],
    actorClass: 'Bandit',
    race: 'Human',
    level: [1,5],
    health: 100,
    maxHealth: 100,
    stamina: 100,
    maxStamina: 100,
    mana: 100,
    maxMana: 100,
    armor: 5,
    dodge: 10,
    focus: 33,
    strength: 10,
    dexterity: 12,
    constitution: 10,
    charisma: 10,
    wisdom: 8,
    intelligence: 5,
    isDead: false,
    hasFocusSpell: false,
    location: 'slums',
    armorFromEquipment: 3,
}