export default 
{
  actorName: 'Javik',
  actorClass: 'Fighter',
  race: 'Human',
  level: 1,
  health: 100,
  maxHealth: 100,
  mana: 100,
  maxMana: 100,
  armor: 5,
  dodge: 10,
  focus: 33,
  strength: 13,
  dexterity: 18,
  constitution: 15,
  charisma: 15,
  wisdom: 13,
  intelligence: 12,
  isDead: false,
  hasFocusSpell: false,
  visited: [],
  location: 'docks',
  expVal: 30,
};