export default {
  actorName: 'Zaster',
  actorClass: 'Wizard',
  race: 'Human',
  level: 1,
  health: 100,
  maxHealth: 100,
  mana: 100,
  maxMana: 100,
  armor: 0,
  dodge: 10,
  focus: 33,
  strength: 10,
  dexterity: 10,
  constitution: 10,
  charisma: 13,
  wisdom: 10,
  intelligence: 13,
  isDead: false,
  hasFocusSpell: false,
  visited: [],
  isPlayer: true,
  exp: 40,
  expToLevel: 100,
  armorFromEquipment: 0,
  canTravelOnMinimap: true,
  refsUnlocked: {
    hunter: true,
    reliquary: true,
    rho: false,
    the_red_moon: false,
  },
  magicFromEquipment: 0,
  attackFromEquipment: 0,
  maxSP: 8,
  sp: 3,
  gold: 9999,
};