export default {
    actorName: 'Audrey',
    actorClass: 'Fighter',
    race: 'Human',
    level: 36,
    health: 435,
    maxHealth: 435,
    mana: 30,
    maxMana: 30,
    armor: 8,
    dodge: 10,
    focus: 1,
    strength: 24,
    dexterity: 10,
    constitution: 14,
    charisma: 13,
    wisdom: 10,
    intelligence: 13,
    isDead: false,
    hasFocusSpell: false,
    visited: [],
    exp: 40,
    expToLevel: 100,
    armorFromEquipment: 0,
    attackFromEquipment: 0,
}